2025-02-12 09:18:46,108 - __main__ - ERROR - ZeroDivisionError: division by zero
2025-02-12 09:18:46,108 - __main__ - ERROR - Exception: division by zero
2025-02-12 09:26:34,814 - __main__ - ERROR - Exception occurred: division by zero
Traceback (most recent call last):
  File "c:\python\BOOK\chapter 16 EXCEPTIONS\Logging the exception\logging5.py", line 15, in <module>
    x = 1 / 0
        ~~^~~
ZeroDivisionError: division by zero
